DELIMITER $

ALTER TABLE STUDENT_AUDIT ADD COLUMN HISTORY_DATE DATE$

ALTER TABLE STUDENT_AUDIT ADD COLUMN ACTION VARCHAR(10)$

ALTER TABLE STUDENT_AUDIT ADD COLUMN USERNAME VARCHAR(50)$

DROP TRIGGER IF EXISTS STUDENT_TRIG_INSERT$

DROP TRIGGER IF EXISTS STUDENT_TRIG_UPDATE$

DROP TRIGGER IF EXISTS STUDENT_TRIG_DELETE$

CREATE TRIGGER STUDENT_TRIG_INSERT AFTER INSERT ON STUDENT FOR EACH ROW
BEGIN
	
		INSERT INTO STUDENT_AUDIT
		(
			STUDENT_ID
			,NAME
			,GENDER
			,COURSEID
			,HISTORY_DATE
			,ACTION
			,USERNAME
		)VALUES
		(
		  NEW.STUDENT_ID
		  ,NEW.NAME
			,NEW.GENDER
			,NEW.COURSEID
			,CURRENT_DATE()
			,'INSERT'
			,USER()
		);

END$


CREATE TRIGGER STUDENT_TRIG_UPDATE AFTER UPDATE ON STUDENT FOR EACH ROW
BEGIN
	
		INSERT INTO STUDENT_AUDIT
		(
			STUDENT_ID
			,NAME
			,GENDER
			,COURSEID
			,HISTORY_DATE
			,ACTION
			,USERNAME
		)VALUES
		(
		  OLD.STUDENT_ID
		  ,OLD.NAME
			,OLD.GENDER
			,NEW.COURSEID
			,CURRENT_DATE()
			,'UPDATE'
			,USER()
		);

END$



CREATE TRIGGER STUDENT_TRIG_DELETE AFTER DELETE ON STUDENT FOR EACH ROW
BEGIN
	
		INSERT INTO STUDENT_AUDIT
		(
			STUDENT_ID
			,NAME
			,GENDER
			,COURSEID
			,HISTORY_DATE
			,ACTION
			,USERNAME
		)VALUES
		(
		  OLD.STUDENT_ID
		  ,OLD.NAME
			,OLD.GENDER
			,OLD.COURSEID
			,CURRENT_DATE()
			,'DELETE'
			,USER()
		);

END$

DELIMITER ;
